---    
- name: Install pre-req packages
  yum: state=present
    name={{ item }}
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - deltarpm
    - ntp # this is required for metrics to work, otherwise node times out of sync cause metric issues

- name: Update packages
  yum: state=latest
    name='*'

- name: Install atomic-openshift-utils
  yum: state=present
    name=atomic-openshift-utils

- name: Install docker
  yum: state=present
    name=docker

- name: Configure insecure-registry local setting for docker
  replace: dest=/etc/sysconfig/docker
    regexp="(\s+)^OPTIONS='--selinux-enabled'"
    replace="\1OPTIONS='--selinux-enabled --insecure-registry 172.30.0.0/16'"

# this is for metrics 
- name: Enable services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - ntpd    

