---    
  - name: check for ddns credentials
    fail:
      msg: Google Domains - GOOGLE_DDNS_USER and GOOGLE_DDNS_PASSWORD environment variable must be set.
    when: ddns_user == '' or ddns_password == ''
    
  - name: install EPEL repo
    yum:
      name: "{{ epel_repo.url }}"
      state: present
    register: result
    until: '"failed" not in result'
    retries: 5
    delay: 10

  - name: import EPEL GPG key
    rpm_key:
      key: "{{ epel_repo.gpg_key_url }}"
      state: present
    
  - name: install packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - bind
    - python-httplib2

  - name: setup named.conf
    template: 
      src: named.conf.j2
      dest: /etc/named.conf
    notify: restart named
    
  - name: setup example zone
    template:
      src: example.com.db.j2
      dest: /var/named/zones/example.com.db
    notify: restart named
  
  - name: setup subdomain zone - for subdomain {{ subdomain }}
    template:
      src: subdomain.db.j2
      dest: "/var/named/zones/{{ subdomain }}.{{ domain }}.db"
    notify: restart named
    tags:
      - update_dns
            
  - name: set the dns external ip on google domains
    uri:
      url: https://domains.google.com/nic/update?hostname={{ nameserver_name }}.{{ domain }}&myip={{ ip.external.dns }}
      method: POST
      user: "{{ ddns_user }}"
      password: "{{ ddns_password }}"
      HEADER_content-length: "0"
      status_code: 200
      return_content: yes
    register: response
    tags:
      - update_dns

  - name: check if google domains authentication was successful
    fail:
      msg: "response from google domains is badauth"
    when: "'badauth' in response.content"
    tags:
      - update_dns
  
  - name: copy the oclogin.sh file root
    template: 
      src: oclogin.sh.j2
      dest: /root/oclogin.sh

  - name: set permissions on file root
    file:
      owner: root
      group: root
      mode: 0755
      path: /root/oclogin.sh 
      
  - name: copy the oclogin.sh file user
    template: 
      src: oclogin.sh.j2
      dest: /home/user/oclogin.sh

  - name: set permissions on file user
    file:
      owner: user
      group: user
      mode: 0755
      path: /home/user/oclogin.sh       