---
- name: update workstation dns configuration
  hosts: workstation
  remote_user: root
  vars_files: 
    - vars.yml
  roles:
    - dns_config
    
- name: update master for dns changes
  hosts: openshift_master
  remote_user: root
  vars_files: 
    - vars.yml        
  roles:
    - ose_master_dns_update
