---
- name: debug
  debug:
    msg: master internal hostname  {{ master_internal_hostname }}
    
- name: Make master schedulable
  command: oadm manage-node {{ master_internal_hostname }} --schedulable=true
  
- name: Add user john
  user: 
    name: john
    state: present

- name: Copy the oclogin.sh file
  template: src=oclogin.sh dest=/home/john/oclogin.sh

- name: Set permissions on file
  file:
    owner: john
    group: john
    mode: 0755
    path: /home/john/oclogin.sh

- name: Add user john to the system:registry
  command: oadm policy add-role-to-user system:registry john  