---
- name: Create directories
  file:
    path: /var/export/vol6
    owner: nfsnobody
    group: nfsnobody
    mode: 0777
    state: directory
    
- name: Add line in file etc exports
  lineinfile: 
   dest: /etc/exports
   insertafter: EOF
   line: /var/export/vol6 *(rw,root_squash,no_wdelay)
  
- name: Modify idmapd with hostname
  lineinfile:
    dest: /etc/idmapd.conf
    regexp: "^Domain = "
    insertafter: "#Domain = "
    line: "Domain = {{ nfs_internal_hostname }}"
  notify: restart_rpcidmapd

- name: replace permissions
  replace:
    dest: /etc/exports
    regexp: 'rw,sync,all_squash'
    replace: 'rw,root_squash,no_wdelay'

- name: copy pv file
  template:
    src: pv.yml.j2
    dest: /root/{{ item }}-pv.yml
  with_items:
    - vol2
    - vol4
    - vol5
    - vol6

- name: restart nfs
  service:
    name: nfs
    state: restarted