---
- host: localhost
  remote_user: root
  vars:
    clean_metrics:
      - oc project openshift-infra
      - oc delete all --selector="metrics-infra"
      - oc delete sa --selector="metrics-infra"
      - oc delete templates --selector="metrics-infra"
      - oc delete secrets --selector="metrics-infra"
      - oc delete pvc --selector="metrics-infra"   
      - oc delete sa metrics-deployer
      - oc delete secret metrics-deployer
    clean_logging:
      - oc project logging
      - oc delete all --selector logging-infra=kibana
      - oc delete all --selector logging-infra=fluentd
      - oc delete all --selector logging-infra=elasticsearch
      - oc delete all --selector logging-infra=curator
      - oc delete all,sa,oauthclient --selector logging-infra=support
      - oc delete secret logging-fluentd logging-elasticsearch logging-es-proxy logging-kibana logging-kibana-proxy logging-kibana-ops-proxy
      - oc delete project logging
  tasks:
    name: clean metrics
    command: "{{ item }}"
    with_items: "{{ clean_metrics }}"
    
    name: clean logging
    command: "{{ item }}"
    with_items: "{{ clean_logging }}"