---    
# before running this, openshift needs to be installed
- hosts: custom_vms
  remote_user: root
  vars:
    folders:
    - { name: vol1, owner: nfsnobody, group: nfsnobody} 
      - { name: vol2, owner: nfsnobody, group: nfsnobody}
      - { name: vol3, owner: nfsnobody, group: nfsnobody} 
      - { name: vol4, owner: nfsnobody, group: nfsnobody}  
      - { name: vol5, owner: nfsnobody, group: nfsnobody}  
      - { name: vol6, owner: nfsnobody, group: nfsnobody}
      - { name: metrics, owner: nfsnobody, group: nfsnobody} 
      - { name: logging, owner: nfsnobody, group: nfsnobody} 
      
  roles:
    - nfs
