---    
# before running this, openshift needs to be installed
- hosts: openshift_master
  remote_user: root
  vars:
    folders:
      - vol1 # logging
      - vol2 # metrics
      - vol3 # registry
      - vol4
      - vol5
  roles:
    - nfs
    - registry
    - router
    - logging
    - metrics
