master_external_ip: 104.197.6.245
infra_external_ip: 104.155.143.68
dns_external_ip: 104.154.250.157
ddns_user: << your user >>
ddns_password: << your pass >>

domain: techknowledgeshare.net
subdomain: ose
nameserver_name: ns1
ose_wildcard: apps

dns_internal_ip: 10.0.0.100
master_internal_ip: 10.0.0.2
infra_internal_ip: 10.0.0.3
node1_internal_ip: 10.0.0.4
node2_internal_ip: 10.0.0.5

ansible_distribution_major_version: 7

epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

master_config: /etc/origin/master/master-config.yaml
original_url: https://master.ose.techknowledgeshare.net
new_url: https://master.{{ subdomain }}.{{ domain }}
old_subdomain: apps.ose.techknowledgeshare.net
new_subdomain: "{{ ose_wildcard }}.{{ subdomain }}.{{ domain }}"
public_master_url: "{{ new_url }}:8443"