---    
# before running this, openshift needs to be installed
# need to edit /etc/dnsmasq.d/origin-upstream-dns.conf with server 
- hosts: openshift_master
  remote_user: root
  vars:
    folders:
      - vol1 # logging
      - vol2 # registry
      - vol3
      - vol4
      - vol5
  roles:
#    - nfs
#    - registry
#    - router
    - logging
    - metrics
