---    
# before running this, openshift needs to be installed
- hosts: openshift_local_master
  remote_user: root
  vars:
    folders:
      - vol1 # logging
      - vol2 # registry
      - vol3
      - vol4
      - vol5
  roles:
    - nfs
    - ose_no_infra # run this if the master is also the infra_node
    - registry
    - router
    - logging
    - metrics
