---
- name: restart network
  service: name=network state=restarted

- name: restart openvswitch
  service: name=openvswitch state=restarted

- name: restart atomic-openshift-node
  service: name=atomic-openshift-node state=restarted
  
- name: restart atomic-openshift-master
  service: name=atomic-openshift-master state=restarted
  ignore_errors: true
  