---
ip:
  external:
    master: "{{ hostvars[groups['openshift_master'][0]].inventory_hostname }}"
    infra: "{{ hostvars[groups['openshift_infra'][0]].inventory_hostname }}"
    dns: "{{ hostvars[groups['workstation'][0]].inventory_hostname }}"
  internal:
    dns: 10.0.0.100
    master: 10.0.0.10
    infra: 10.0.0.20
    node1: 10.0.0.30
    node2: 10.0.0.31

ansible_distribution_major_version: 7

epel_repo:
  url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

