---
- name: Change the oc context
  command: "oc config use-context {{ default_context }}"

- name: Switch to default project
  command: oc project default

- name: Patch to support infrastructure components witin region=infra
  command: oc patch namespace/default -p '{"metadata":{"annotations":{"openshift.io/node-selector":"region=infra"}}}'

- name: Make master schedulable
  command: oadm manage-node {{ master_hostname }} --schedulable=true

- name: Add user john
  user: 
    name: john
    state: present

- name: Copy the oclogin.sh file
  template: src=oclogin.sh dest=/home/john/oclogin.sh

- name: Set permissions on file
  file:
    owner: john
    group: john
    mode: 0755
    path: /home/john/oclogin.sh

- name: Add user john to the system:registry
  command: oadm policy add-role-to-user system:registry john

- name: Create docker mount path
  file:
    mode: 0777
    path: /mnt/docker
    state: directory

- name: Check whether a registry exists or not
  command: oadm registry --dry-run
  register: registry_out
  ignore_errors: true

- name: Install the registry
  command: >
    oadm registry --config=/etc/origin/master/admin.kubeconfig
    --credentials=/etc/origin/master/openshift-registry.kubeconfig
    --images='{{ registry_url }}'
    --selector='region=infra'
    --mount-host=/mnt/docker
    --service-account=registry 
  when: registry_out | failed