apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The broker's OpenWire port service.
  name: amq-tcp
spec:
  ports:
  - port: 61616
    protocol: TCP
    targetPort: 61616
    nodePort: 30001
  selector:
    deploymentConfig: broker-amq
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

